# Generated by Django 5.2.8 on 2025-11-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1_uz', '1-kurs'), ('1_ru', '1 курс'), ('2_uz', '2-kurs'), ('2_ru', '2 курс'), ('3_uz', '3-kurs'), ('3_ru', '3 курс'), ('4_uz', '4-kurs'), ('4_ru', '4 курс')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=20)),
                ('weekday', models.CharField(choices=[('du', 'Dushanba'), ('se', 'Seshanba'), ('ch', 'Chorshanba'), ('pa', 'Payshanba'), ('ju', 'Juma'), ('sh', 'Shanba')], max_length=10)),
                ('time_pair', models.CharField(choices=[('1', '08:30–09:50'), ('2', '10:00–11:20'), ('3', '11:30–12:50'), ('4', '13:00–14:20'), ('5', '14:30–15:50'), ('6', '16:00–17:20')], max_length=2)),
                ('week_type', models.CharField(choices=[('all', 'Har hafta'), ('even', 'Juft'), ('odd', 'Toq')], default='all', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
            ],
        ),
    ]
