# Generated by Django 5.2.8 on 2025-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('1', '1-kurs'), ('2', '2-kurs'), ('3', '3-kurs'), ('4', '4-kurs')], max_length=50, unique=True),
        ),
    ]
